steal(
    './models/models.js',
    './fixtures/fixtures.js'
).then(
    './controllers/controllers.js',
    './public/css.js'
).then(
    'public/js/libs/jqueryui/latest.js'
).then(
    'public/js/libs/bootstrap/bootstrap.js'
);